### PR TITLE
Added popup styling for mapbox

### PR DESCRIPTION
**Pull request by Kyruel87**
Styled mapbox popups

### CODE REVIEW

**Comment by lambley** [comment]
image
Can you fix the close button styling before merging?

**Comment by lambley** [comment]
also add some padding - 4px all around should be enough

**Comment by Kyruel87** [comment]
> also add some padding - 4px all around should be enough

For the text or the image? I purposefully left off padding for the image as I like that look. Will do the close button now

**Comment by Kyruel87** [comment]
> also add some padding - 4px all around should be enough

Got the inspiration from this:

https://images.app.goo.gl/6cCVM3UTPZvv8qud9

**Comment by lambley** [comment]
add padding the text box underneath the image - text is too close to the border

**Comment by Kyruel87** [comment]
> add padding the text box underneath the image - text is too close to the border

Cool, all done!

**Pull request merged**
